import Head from "next/head";
import { AnimationDelay } from "../contents/animation-delay";
import { AnimationComposition } from "../contents/animation-composition";
import { AnimationDirection } from "../contents/animation-direction";
import { BackgroundAttachment } from "../contents/background-attachment";
import { BoxSizing } from "@/contents/box-sizing";
import { Margin } from "@/contents/margin";
import { CustomProperty } from "@/contents/custom-property";

export default function Home() {
  return (
    <>
      <Head>
        <title>CSS Explanation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="container">
        <h1>CSS Explanation</h1>
        <h2>アニメーション</h2>
        <AnimationComposition></AnimationComposition>
        <AnimationDelay></AnimationDelay>
        <AnimationDirection></AnimationDirection>
        <h2>背景と境界線</h2>
        <BackgroundAttachment></BackgroundAttachment>
        <h2>基本インターフェース</h2>
        <BoxSizing></BoxSizing>
        <h2>ボックス配置</h2>
        <h2>ボックスモデル</h2>
        <Margin></Margin>
        <h2>カスタムプロパティ</h2>
        <CustomProperty></CustomProperty>
      </div>
    </>
  );
}
