import Head from "next/head";
import { AnimationDelay } from "../contents/animation-delay";
import { AnimationComposition } from "../contents/animation-composition";
import { AnimationDirection } from "../contents/animation-direction";
import { BackgroundAttachment } from "../contents/background-attachment";

export default function Home() {
  return (
    <>
      <Head>
        <title>CSS Explanation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="container">
        <h1>CSS Explanation</h1>
        <h2>Animations</h2>
        <AnimationComposition></AnimationComposition>
        <AnimationDelay></AnimationDelay>
        <AnimationDirection></AnimationDirection>
        <h2>Backgrounds and Borders</h2>
        <BackgroundAttachment></BackgroundAttachment>
      </div>
    </>
  );
}
